Numpy is faster than list or looping. Because ndarray uses contiguous block of memory, rather than random locations at memory and then pointing to them.

But that means NumPy arrays have a fixed size and must be homogeneous (all elements of same type)

In [2]:
def python_forloop_list_approach(x, w):
    z = 0.
    for i in range(len(x)):
        z += x[i] * w[i]
    return z

a = [1., 2., 3.]
b = [4., 5., 6.]

large_a_list = list(range(10000))
large_b_list = list(range(10000))

%timeit python_forloop_list_approach(large_a_list, large_b_list)

296 μs ± 8.05 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


Let's try using numpy's dot() method.

In [3]:
import numpy as np

def numpy_dotproduct_approach(x, w):
    # same as np.dot(x, w)
    # same as x @ w
    return x.dot(w)


large_a_ndarray = np.arange(10000)
large_b_ndarray = np.arange(10000)

%timeit numpy_dotproduct_approach(large_a_ndarray, large_b_ndarray)

3.54 μs ± 97.1 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


# N-dimensional Arrays

In [4]:
a = [1., 2., 3.]

np.array(a)

array([1., 2., 3.])

In [5]:
lst = [[1, 2, 3],
       [4, 5, 6]]

ary2d = np.array(lst)
ary2d

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
ary2d.dtype

dtype('int64')

In [7]:
# Pass dtype= parameter to tell NumPy which type to use instead of infering
int32_ary_1 = np.array(lst, dtype=np.int32)
display(int32_ary_1.dtype)

# or convert existing array to another dtype
int32_ary_2 = ary2d.astype(np.int32)
display(int32_ary_2)


float32_ary = ary2d.astype(np.float32)
display(float32_ary)


display(float32_ary.dtype)

dtype('int32')

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

dtype('float32')

We can find out the dimensions of an array using `ndim`. Or number of elements in each dimensions, use `shape`

In [8]:
display(ary2d)

display(ary2d.ndim)

display(ary2d.shape)

print(len(ary2d.shape))  # equivalent to ndim

array([[1, 2, 3],
       [4, 5, 6]])

2

(2, 3)

2


# Array Construction Routines
We can create arrays of different dimensions with some default values.

In [9]:
np.ones((3, 4), dtype=np.int64)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [10]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.zeros((3, 3), dtype=np.int64)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [12]:
np.zeros((3, 3)) + 99

array([[99., 99., 99.],
       [99., 99., 99.],
       [99., 99., 99.]])

In [13]:
np.empty((3, 4)) # Fills with nonsensical values from memory

array([[3.68775179e-315, 0.00000000e+000, 1.33685735e-312,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 6.30712199e-310,
        6.30712204e-310],
       [1.33685735e-312, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000]])

In [14]:
# Identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
# Diagonal Matrix
np.diag((1, 2, 3))

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [16]:
np.arange(4, 10)

array([4, 5, 6, 7, 8, 9])

In [17]:
np.arange(1., 11., 0.1)

array([ 1. ,  1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,
        2.1,  2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,
        3.2,  3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,
        4.3,  4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,
        5.4,  5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,
        6.5,  6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,
        7.6,  7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,
        8.7,  8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,
        9.8,  9.9, 10. , 10.1, 10.2, 10.3, 10.4, 10.5, 10.6, 10.7, 10.8,
       10.9])

In [18]:
np.linspace(6., 15., num=10)

array([ 6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15.])

# Array Indexing

In [19]:
ary = np.array([1,2,3])
display(ary[0])

display(ary[0:3])

np.int64(1)

array([1, 2, 3])

In [20]:
ary = np.array([[1,2,3],
                [4,5,6]])

display(ary[0, -2]) # First row, second from last element

display(ary[-1, -1]) # Lower right

display(ary[1, 1])  # First row, second column

display(ary[:, 0]) # Entire first column

display(ary[:, :2]) # First two columns

np.int64(2)

np.int64(6)

np.int64(5)

array([1, 4])

array([[1, 2],
       [4, 5]])

### Ufuncs in NumPy
Used to vectorize operations.

In [21]:
lst = [[1, 2, 3],
       [4, 5, 6]]  # 2d array

for row_idx, row_val in enumerate(lst):
    for col_idx, col_val in enumerate(row_val):
        lst[row_idx][col_idx] += 1

lst

[[2, 3, 4], [5, 6, 7]]

In [22]:
%%timeit

# the same can be achieved with list comprehensions

[[cell +1 for cell in row] for row in lst]

254 ns ± 6.54 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [23]:
ary = np.array([[1, 2, 3],
                [4, 5, 6]])

In [24]:
%%timeit

# Easier still using NumPy's ufunc for element-wise scalar addition



ary2 = np.add(ary, 1)

ary

395 ns ± 9.42 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [25]:
np.add(ary, 1)

array([[2, 3, 4],
       [5, 6, 7]])

In [26]:
# Same as np.add(ary, 1)

ary + 1

array([[2, 3, 4],
       [5, 6, 7]])

In [27]:
np.power(ary, 2)

array([[ 1,  4,  9],
       [16, 25, 36]])

In [31]:
# Same as np.power(ary, 2)

ary**2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [32]:
np.sqrt(ary)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

To compute the sum or product of array element along a given axis, we can use `reduce`. By default, `reduce` applies an operation along the first axis (`axis=0`). In the case of a two-dimensional array, we can think of the first axis as the rows of a matrix.

In [34]:
# Adding up elements along rows yields the column sums of that matrix

ary = np.array([[1, 2, 3],
                [4, 5, 6]])

np.add.reduce(ary, axis=0)

array([5, 7, 9])