In [2]:
# Import torch and check if GPU is available

import torch
torch.__version__

'2.8.0+cu126'

In [3]:
torch.cuda.is_available()

True

Torch uses NumPy like API for tensors.

In [4]:
tensor0d = torch.tensor(1)
display(tensor0d)

tensor1d = torch.tensor([1, 2, 3])
display(tensor1d)

tensor2d = torch.tensor([[1, 2], [3, 4]])
display(tensor2d)

tensor3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
display(tensor3d)

tensor(1)

tensor([1, 2, 3])

tensor([[1, 2],
        [3, 4]])

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])

In [5]:
print(tensor1d.dtype)

torch.int64


In [6]:
floatvec = torch.tensor([1.0, 2.0, 3.0])
print(floatvec.dtype)

torch.float32


In [7]:
# Change dtype of an existing tensor
floatvec = tensor1d.to(torch.float32)
print(floatvec.dtype)

torch.float32


In [8]:
tensor2d = torch.tensor([[1, 2, 3],
                         [4, 5, 6]])

display(tensor2d)

tensor2d.shape

tensor([[1, 2, 3],
        [4, 5, 6]])

torch.Size([2, 3])